# Generated by Django 6.0.3 on 2026-03-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='url',
            field=models.URLField(max_length=1024, verbose_name='Original URL'),
        ),
    ]
